### ISSUE TITLE
Clarify usage

### ISSUE THREAD

**Issue by axilleas** [gjtorikian/nanoc-redirector#2]
Hi! Thanks for the plugin :) I have one question. In the readme you write that you need to add in the `Rules` file the following:

```ruby
postprocess do
  REPS.each do |rep|
    @items.each do |item|
      NanocRedirector::RedirectFrom.process(item, item.path(rep: rep))
    end
  end
end
```

So, what is `REPS` referring to?

**Comment by axilleas** [comment]
@gjtorikian just getting your attention :)

**Comment by gjtorikian** [comment]
Ah, `REPS` stood for [representations](https://nanoc.ws/doc/items-and-layouts/), which I was using in another project. But it's by no means required here. In https://github.com/gjtorikian/nanoc-redirector/commit/3416691d5eb7fd1f77a053e37fa1f3f35aa9e9ed I simplified the example. Thanks for noticing!

**Comment by axilleas** [comment]
Ah, great thanks, that makes sense now :)
