### ISSUE TITLE
use @config[:output_dir] and update postprocess example

### ISSUE THREAD

**Issue by joerggollnick** [gjtorikian/nanoc-redirector#5]
I like to have a unified setup for all my sites. This includes a non default output_dir setting to public.

Easiest was to extend RedirectFrom with a output_dir parameter and adapt Rules file.
```
postprocess do
  @items.each do |item|
    NanocRedirector::RedirectFrom.process(item, item.identifier.without_ext, @config[:output_dir])
  end
end
```

**Comment by gjtorikian** [comment]
Is this a question for me, or...?

**Comment by joerggollnick** [comment]
Yes question is how to implement best:
Add one parameter for @config array or parameter for output_dir?
Should I create a pull request for this or attach changed files as comment?
